ci: build: check for CRLF issues in YAML profiles
Its quite common these days to use GitLab's web based file editor to
save some edit/save/push development cycles, but on the other hand it
might introduce hard to debug/random issues here and there, so lets make
it clear, that something went wrong and prevent those possibly faulty
builds.

Signed-off-by: Petr Štetiar <ynezz@true.cz>

diff --git a/.gitlab/build.yml b/.gitlab/build.yml
--- a/.gitlab/build.yml
+++ b/.gitlab/build.yml
@@ -21,6 +21,17 @@
     - set -o pipefail
     - git config --global --add safe.directory '*'
 
+    - |
+      crlf_check_failed=$(rgrep -U $'\x0D' profiles | cut -d: -f1 | sort -u)
+      if test -n "$crlf_check_failed"; then
+        echo -e "ERROR: detected CRLF issues in the following YAML profiles:\n"
+        for profile in $crlf_check_failed; do
+          echo " * $profile"
+        done
+        echo -e "\nIt might result in hard to debug issues, please fix them."
+        exit 1
+      fi
+
     - >
       if echo "$CI_RUNNER_DESCRIPTION" | grep -v -q "Restricted.*OSP"; then
         sed -i -E 's;git.openwrt.org/(feed|project);github.com/openwrt;' feeds.conf.default
