ci: build: show detailed log output from package/install build step
It seems, that `package/install` build step is not providing error
output in the `BUILD_LOG_DIR` log files, so lets run it again on build
failure and provide output in the CI job log output directly.

Signed-off-by: Petr Štetiar <ynezz@true.cz>

diff --git a/.gitlab/build.yml b/.gitlab/build.yml
--- a/.gitlab/build.yml
+++ b/.gitlab/build.yml
@@ -58,6 +58,16 @@
         popd > /dev/null
       done
 
+    - >
+      trap "
+        grep -qz 'package/install[[:space:]]make -r world' logs/build.log && {
+          echo '[!] ERROR: package/install seems to fail, enabling verbose output'
+          make package/install V=s 2>&1 | tee --append logs/build.log
+          grep -C5 'Collected errors:' logs/build.log
+        }
+        echo '[!] ERROR: build failed'
+        exit 1
+      " ERR
     - make -j $(nproc) 2>&1 | tee --append logs/build.log
     - rm .build_failed
 
